// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Supabase 권장: 런타임은 pooler(DATABASE_URL), 마이그레이션은 direct(DIRECT_URL)
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
